### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by davidshumway** [agaveplatform/developer-docs#2]
From the main page of docs (https://docs.agaveplatform.org/#introduction), the following links are broken and returning 404:

CHANGELOG (https://github.com/agaveplatform/science-apis/src/master/CHANGELOG.md)
Issues (https://support.agaveplatform.org/)
Knowledge Base (https://support.agaveplatform.org/)

**Comment by deardooley** [comment]
Thanks for the issue. I have updated the documentation. User registration is temporarily down due to an API change by our email provider. We expect to have service restored within the day. If you would like an account before then, please reach out on our Slack channel https://slackin.agaveplatform.org, or reach out to me directly and I'll set you up.
